services:
  wpg-weather-web:
    image: ghcr.io/ch604/wpg-weather-web:latest
    container_name: wpg-weather-web
    restart: unless-stopped
    ports:
      - 5000:5000
    dns:
      - 1.1.1.1
      - 1.0.0.1
    environment:
      - "WPG_HOMEZIP=48205"
      - "WPG_MUSIC=ON"
      - "WPG_RSSFEED=https://www.wxyz.com/news/region/detroit.rss"