[tool.mypy]
disable_error_code = "import-untyped,import-not-found"

[tool.yapf]
based_on_style = "google"
indent_width = 2
continuation_indent_width = 2
column_limit = 120
blank_lines_between_top_level_imports_and_variables = 2
